query getRootCategories($type: String) {
  categories(filters: { type: { eq: $type } }) {
    data {
      attributes {
        slug
        title
        parent {
          data {
            attributes {
              title
            }
          }
        }
        items {
          data {
            attributes {
              title
              slug
              image {
                data {
                  attributes {
                    url
                  }
                }
              }
            }
          }
        }
        image {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}

query getCategoryBySlug($slug: String) {
  categories(filters: { slug: { eq: $slug } }) {
    data {
      attributes {
        slug
        title
        showProducts
        showRelated
        parent {
          data {
            attributes {
              title
              slug
            }
          }
        }
        items {
          data {
            attributes {
              title
              slug
              image {
                data {
                  attributes {
                    url
                  }
                }
              }
            }
          }
        }
        related {
          data {
            attributes {
              title
              slug
              image {
                data {
                  attributes {
                    url
                  }
                }
              }
            }
          }
        }
      }
    }
  }
   brands(filters: { products: { category: { slug: { eq: $slug } } } }) {
    data {
      id
      attributes {
        title
      }
    }
  }
}

