query CatalogMenu {
  categories(
    filters: { showInNav: { eq: true }, and: { type: { eq: "section" } } }
  ) {
    data {
      id
      attributes {
        title
        navIcon {
          data {
            attributes {
              url
            }
          }
        }
        items(
          filters: {
            showInNav: { eq: true }
            and: { type: { eq: "category" } }
          }
        ) {
          data {
            id
            attributes {
              title
              slug
              items(
                filters: {
                  showInNav: { eq: true }
                  and: { type: { eq: "subcategory" } }
                }
              ) {
                data {
                  id
                  attributes {
                    title
                    slug
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

query SearchEntitiesByTitle($value: String) {
  categories(filters: { title: { contains: $value } }) {
    data {
      id
      attributes {
        title
        slug
      }
    }
  }
  products(filters: { title: { contains: $value } }) {
    data {
      id
      attributes {
        title
        article
        parent {
          data {
            attributes {
              slug
            }
          }
        }
      }
    }
  }
}
query MainSearch($value: String) {
  products(filters: { article: { eq: $value } }) {
    data {
      attributes {
        article
        parent {
          data {
            attributes {
              slug
            }
          }
        }
      }
    }
  }
  categories(filters: { title: { contains: $value } }) {
    data {
      attributes {
        slug
      }
    }
  }
}
