query ProductByArticle($article: String) {
  products(filters: { article: { eq: $article } }) {
    data {
      attributes {
        article
        title
        price
        amount
        description {
          value
        }
        color {
          value
          title
        }
        size {
          value
        }
        images {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}

query ProductCardDataBySlug($slug: String) {
  productCards(filters: { slug: { eq: $slug } }) {
    data {
      attributes {
        title
        slug
        images {
          data {
            id
            attributes {
              url
            }
          }
        }
        items {
          data {
            attributes {
              article
              color {
                title
                value
              }
              size {
                value
              }
            }
          }
        }
        testCategory {
          data {
            attributes {
              title
              slug
            }
          }
        }
      }
    }
  }
}

query ProductsBySubcategorySlug($slug: String) {
  products(filters: { parent: { testCategory: { slug: { eq: $slug } } } }) {
    data {
      attributes {
        title
        article
        price
        color {
          title
        }
        size {
          value
        }
        parent {
          data {
            attributes {
              slug
            }
          }
        }
        images {
          data {
            id
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
