// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'PrometeiFooter': typeof import("../components/PrometeiFooter.vue")['default'],
    'PrometeiHeader': typeof import("../components/PrometeiHeader.vue")['default'],
    'ExpandMenu': typeof import("../components/ExpandMenu/ExpandMenu.vue")['default'],
    'ExpandMenuContentItem': typeof import("../components/ExpandMenu/ExpandMenuContentItem.vue")['default'],
    'UIAmountCounter': typeof import("../components/UI/AmountCounter.vue")['default'],
    'UIImageViewer': typeof import("../components/UI/ImageViewer.vue")['default'],
    'UITab': typeof import("../components/UI/Tab.vue")['default'],
    'UITabsWrapper': typeof import("../components/UI/TabsWrapper.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyPrometeiFooter': typeof import("../components/PrometeiFooter.vue")['default'],
    'LazyPrometeiHeader': typeof import("../components/PrometeiHeader.vue")['default'],
    'LazyExpandMenu': typeof import("../components/ExpandMenu/ExpandMenu.vue")['default'],
    'LazyExpandMenuContentItem': typeof import("../components/ExpandMenu/ExpandMenuContentItem.vue")['default'],
    'LazyUIAmountCounter': typeof import("../components/UI/AmountCounter.vue")['default'],
    'LazyUIImageViewer': typeof import("../components/UI/ImageViewer.vue")['default'],
    'LazyUITab': typeof import("../components/UI/Tab.vue")['default'],
    'LazyUITabsWrapper': typeof import("../components/UI/TabsWrapper.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  }
}
export const PrometeiFooter: typeof import("../components/PrometeiFooter.vue")['default']
export const PrometeiHeader: typeof import("../components/PrometeiHeader.vue")['default']
export const ExpandMenu: typeof import("../components/ExpandMenu/ExpandMenu.vue")['default']
export const ExpandMenuContentItem: typeof import("../components/ExpandMenu/ExpandMenuContentItem.vue")['default']
export const UIAmountCounter: typeof import("../components/UI/AmountCounter.vue")['default']
export const UIImageViewer: typeof import("../components/UI/ImageViewer.vue")['default']
export const UITab: typeof import("../components/UI/Tab.vue")['default']
export const UITabsWrapper: typeof import("../components/UI/TabsWrapper.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyPrometeiFooter: typeof import("../components/PrometeiFooter.vue")['default']
export const LazyPrometeiHeader: typeof import("../components/PrometeiHeader.vue")['default']
export const LazyExpandMenu: typeof import("../components/ExpandMenu/ExpandMenu.vue")['default']
export const LazyExpandMenuContentItem: typeof import("../components/ExpandMenu/ExpandMenuContentItem.vue")['default']
export const LazyUIAmountCounter: typeof import("../components/UI/AmountCounter.vue")['default']
export const LazyUIImageViewer: typeof import("../components/UI/ImageViewer.vue")['default']
export const LazyUITab: typeof import("../components/UI/Tab.vue")['default']
export const LazyUITabsWrapper: typeof import("../components/UI/TabsWrapper.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
